import { Outfit } from "next/font/google";
import "./globals.css";

// Importing Outfit font from Google Fonts
const outfitFont = Outfit({
    subsets: ["latin"],
    variable: "--font-outfit",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${outfitFont.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
